export const PRODUCTS = [
  {
    id: "digest",
    name: "Digest +",
    subtitle: "100 Tabletas",
    category: "probioticos",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/3cb732c65_hf_20260205_004452_1db89493-a0fd-4f65-b399-a8bf40d8a5a6.png",
    palette: { bg: "#1a3a2a", accent: "#4CAF50", soft: "#81C784", light: "#E8F5E9", text: "#FFFFFF" },
    emoji: "🌿",
    tagline: "Digestión perfecta. Nutrición máxima.",
    benefits: ["Enzimas digestivas activas", "Mejora absorción de nutrientes", "Elimina gases y cólicos", "Fortalece flora intestinal"],
    ingredients: "Amilasa · Proteasa · Lipasa · Probióticos"
  },
  {
    id: "urinary",
    name: "Urinary +",
    subtitle: "100 Pastillas",
    category: "vitaminas",
    price: 390,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/3104a4820_hf_20260205_004620_4d0935aa-7b59-40b0-b84a-35618af5891a.png",
    palette: { bg: "#0d2137", accent: "#2196F3", soft: "#64B5F6", light: "#E3F2FD", text: "#FFFFFF" },
    emoji: "💧",
    tagline: "Tracto urinario sano, mascota feliz.",
    benefits: ["D-Manosa bloquea bacterias E. coli", "Extracto de arándano antioxidante", "Previene infecciones recurrentes", "Apoya vejiga y riñones"],
    ingredients: "D-Manosa · Arándano · Vitamina C · Zinc"
  },
  {
    id: "mobility",
    name: "Mobility +",
    subtitle: "100 Tabletas",
    category: "articulaciones",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/1fd5818d5_hf_20260205_005545_fac59ea8-1ae9-428b-9e73-464609c2702f.png",
    palette: { bg: "#1a2744", accent: "#FF9800", soft: "#FFB74D", light: "#FFF3E0", text: "#FFFFFF" },
    emoji: "🏃",
    tagline: "Muévete sin dolor. Vive sin límites.",
    benefits: ["Glucosamina regenera cartílago", "Condroitina lubrica articulaciones", "MSM reduce inflamación", "Ideal para razas grandes y activas"],
    ingredients: "Glucosamina · Condroitina · MSM · Vitamina E"
  },
  {
    id: "artro",
    name: "Artro +",
    subtitle: "100 Tabletas",
    category: "articulaciones",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/56a4949ba_hf_20260205_005523_1c182387-9dbc-4381-8e99-a3fdaf178901.png",
    palette: { bg: "#2d1b00", accent: "#FF6F00", soft: "#FFA726", light: "#FFF8E1", text: "#FFFFFF" },
    emoji: "💪",
    tagline: "Articulaciones fuertes. Cada paso cuenta.",
    benefits: ["Fórmula avanzada glucosamina+condroitina", "Frena el desgaste articular", "Antiinflamatorio natural", "Resultados desde la 1ra semana"],
    ingredients: "Glucosamina HCl · Condroitina · Colágeno tipo II"
  },
  {
    id: "vision",
    name: "Vision +",
    subtitle: "100 Tabletas",
    category: "vitaminas",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/84f1e4bea_hf_20260205_005013_73aee6fa-0bbe-4811-9962-70026fd1c76e.png",
    palette: { bg: "#0f1f3d", accent: "#7C4DFF", soft: "#B39DDB", light: "#EDE7F6", text: "#FFFFFF" },
    emoji: "👁️",
    tagline: "Que vean el mundo con claridad.",
    benefits: ["Luteína protege retina", "Zeaxantina filtra luz azul dañina", "Vitamina A esencial para visión nocturna", "Previene cataratas prematuras"],
    ingredients: "Luteína · Zeaxantina · Vitamina A · Zinc"
  },
  {
    id: "alergy",
    name: "Alergy +",
    subtitle: "100 Tabletas",
    category: "piel_pelaje",
    price: 410,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/9aac856e1_hf_20260205_004429_18b723d5-1e62-4d77-a0d9-91bd2a85324c.png",
    palette: { bg: "#1f0a2e", accent: "#E91E63", soft: "#F06292", light: "#FCE4EC", text: "#FFFFFF" },
    emoji: "🌸",
    tagline: "Adiós a la picazón. Hola piel sana.",
    benefits: ["Reduce picazón y enrojecimiento", "Quercetina antihistamínico natural", "Fortalece barrera cutánea", "Alivia dermatitis y eccemas"],
    ingredients: "Quercetina · Omega 3 · Biotina · Vitamina E"
  },
  {
    id: "gymgo",
    name: "Gymgo +",
    subtitle: "100 Tabletas",
    category: "vitaminas",
    price: 390,
    imageUrl: null,
    palette: { bg: "#0a2818", accent: "#00BCD4", soft: "#4DD0E1", light: "#E0F7FA", text: "#FFFFFF" },
    emoji: "🧠",
    tagline: "Mente ágil. Energía sin límites.",
    benefits: ["Ginkgo Biloba mejora circulación cerebral", "Refuerza memoria y cognición", "Ideal para perros mayores", "Antioxidante neuroprotector"],
    ingredients: "Ginkgo Biloba · Coenzima Q10 · Vitamina B12"
  },
  {
    id: "bronqui",
    name: "Bronqui +",
    subtitle: "100 Tabletas",
    category: "vitaminas",
    price: 390,
    imageUrl: null,
    palette: { bg: "#0d2233", accent: "#00ACC1", soft: "#4FC3F7", light: "#E1F5FE", text: "#FFFFFF" },
    emoji: "🫁",
    tagline: "Respira profundo. Vive más.",
    benefits: ["Broncodilatador natural", "Reduce mucosidad y tos crónica", "Fortalece vías respiratorias", "Extractos de plantas medicinales"],
    ingredients: "Hedera Helix · Timol · N-Acetilcisteína · Zinc"
  },
  {
    id: "senior",
    name: "Senior +",
    subtitle: "100 Tabletas",
    category: "vitaminas",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/665de64be_hf_20260205_003334_01f9f8c8-eafc-4e7f-a6d6-53ccb436c818.png",
    palette: { bg: "#2a1a00", accent: "#FFC107", soft: "#FFD54F", light: "#FFFDE7", text: "#FFFFFF" },
    emoji: "🌟",
    tagline: "La edad es solo un número.",
    benefits: ["Coenzima Q10 energía celular", "Antioxidantes contra envejecimiento", "Apoya corazón y circulación", "Vitaminas B para sistema nervioso"],
    ingredients: "CoQ10 · Vitamina E · Selenio · Complejo B"
  },
  {
    id: "cartilag",
    name: "Cartilag +",
    subtitle: "100 Tabletas",
    category: "articulaciones",
    price: 380,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/2f1356149_hf_20260205_003819_37d2dde4-3e60-48d3-88aa-555c408081fe.png",
    palette: { bg: "#1a0a2e", accent: "#9C27B0", soft: "#CE93D8", light: "#F3E5F5", text: "#FFFFFF" },
    emoji: "🦴",
    tagline: "Cartílago protegido. Vida activa.",
    benefits: ["Colágeno tipo II regenera cartílago", "Silicio orgánico fortalece tejido", "Ácido hialurónico lubrica articulaciones", "Reduce desgaste por edad y ejercicio"],
    ingredients: "Colágeno tipo II · Silicio orgánico · Ácido hialurónico"
  },
  {
    id: "derma",
    name: "Derma +",
    subtitle: "100 Tabletas",
    category: "piel_pelaje",
    price: 350,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/a21bf32ab_hf_20260205_005140_abfd3a66-27c5-45a4-8920-63e9ec953e07.png",
    palette: { bg: "#1a0f00", accent: "#FF8F00", soft: "#FFB300", light: "#FFF8E1", text: "#FFFFFF" },
    emoji: "✨",
    tagline: "Pelaje brillante. Piel radiante.",
    benefits: ["Omega 3 EPA+DHA hidrata piel", "Biotina fortalece pelo y uñas", "Zinc reduce caída de pelo", "Pelaje 3x más brillante en 30 días"],
    ingredients: "Omega 3 · Biotina · Zinc · Vitamina E"
  },
  {
    id: "lifequality",
    name: "Life Quality +",
    subtitle: "Senior · 100 Tabs",
    category: "vitaminas",
    price: 390,
    imageUrl: null,
    palette: { bg: "#0a1f2e", accent: "#26C6DA", soft: "#80DEEA", light: "#E0F7FA", text: "#FFFFFF" },
    emoji: "💎",
    tagline: "Premium para quienes más quieres.",
    benefits: ["Fórmula premium multivitamínica", "Apoya 6 sistemas simultáneos", "Exclusivo para mascotas mayores", "Calidad de vida comprobada"],
    ingredients: "Multivitamínico · CoQ10 · Omega 3 · Antioxidantes"
  },
  {
    id: "calm",
    name: "Calm +",
    subtitle: "100 Tabletas",
    category: "vitaminas",
    price: 360,
    imageUrl: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69817b346a2e239014eef625/c6fee6483_hf_20260205_005537_e7e568e4-a45e-4468-8204-46a5d0dd3b3e.png",
    palette: { bg: "#0a0a2e", accent: "#5C6BC0", soft: "#9FA8DA", light: "#E8EAF6", text: "#FFFFFF" },
    emoji: "🌙",
    tagline: "Calma natural. Sin somnolencia.",
    benefits: ["Triptófano precursor de serotonina", "Reduce ansiedad por separación", "Calma miedos a ruidos fuertes", "Sin sedantes ni efectos secundarios"],
    ingredients: "L-Triptófano · Valeriana · Melatonina · Magnesio"
  }
];
